import numpy as np
from src.envs.LevelForagingEnv import Agent, Task

MAS_DUO = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='l1',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=1.),
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_STRONG = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='l1',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=1.),
        Agent(index='l2',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=1.),
        Agent(index='l3',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=1.),
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}


MAS_WEAK = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='l1',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.35),
        Agent(index='l2',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.35), 
        Agent(index='l3',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.35), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_MIX = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='l1',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.7),
        Agent(index='l2',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.5), 
        Agent(index='l3',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.35), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_WRONG = {
    # Scenario 0: The Warehouse (Square PO Foraging Scenario)
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='l1',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.7),
        Agent(index='l2',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.5), 
        Agent(index='l3',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.5,angle=1.,level=.35), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l4','l5','l6'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_5TEAM = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='1a',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.5),
        Agent(index='2a',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='3a',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='2b',atype='l2',position=(8,3),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='3b',atype='l3',position=(11,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_7TEAM = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='1a',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.),
        Agent(index='2a',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='3a',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='2b',atype='l2',position=(8,3),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='3b',atype='l3',position=(9,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='1b',atype='l1',position=(10,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='2c',atype='l2',position=(11,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_9TEAM = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='1a',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.),
        Agent(index='2a',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='3a',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='2b',atype='l2',position=(8,3),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='3b',atype='l3',position=(9,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='1b',atype='l1',position=(10,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='2c',atype='l2',position=(11,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.), 
        Agent(index='3c',atype='l3',position=(8,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='2d',atype='l2',position=(11,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=1.), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}

MAS_11TEAM = {
    'dim': (20,20), 'type_knowledge': False, 'parameter_knowledge': True, 'vision_block': False,
    'agents' : [
        Agent(index='A',atype=None,position=(10,1),
                direction=1*np.pi/2,
                radius=.2, angle=.3,
                level=1.), 
        Agent(index='1a',atype='l1',position=(9,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.),
        Agent(index='2a',atype='l2',position=(8,1),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='3a',atype='l3',position=(11,1),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='2b',atype='l2',position=(8,3),
                direction=1*np.pi/2,radius=.75,angle=1.,level=.3), 
        Agent(index='3b',atype='l3',position=(9,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='1b',atype='l1',position=(10,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='2c',atype='l2',position=(11,3),
                direction=1*np.pi/2,radius=.5,angle=.5,level=1.), 
        Agent(index='3c',atype='l3',position=(8,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='1c',atype='l1',position=(9,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=.7), 
        Agent(index='2d',atype='l2',position=(10,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=1.), 
        Agent(index='3d',atype='l3',position=(11,18),
                direction=3*np.pi/2,radius=.5,angle=.5,level=1.), 
            ],
    'adhoc_agent_index' : 'A', 'template_types':['l1','l2','l3'], 'impostor_index': None,
    'tasks' : [
        Task(index='0',position=(11,0),level=1.0),
        Task(index='1',position=(10,18),level=1.0),
        Task(index='2',position=(9,10),level=1.0),
        Task(index='A0',position=(1,1),level=1.0),
            Task(index='A1',position=(3,3),level=1.0),
            Task(index='A2',position=(1,3),level=1.0),
            Task(index='A3',position=(3,1),level=1.0),
        Task(index='B0',position=(18,1),level=1.0),
            Task(index='B1',position=(18,3),level=1.0),
            Task(index='B2',position=(16,3),level=1.0),
            Task(index='B3',position=(16,1),level=1.0),
        Task(index='C0',position=(18,18),level=1.0),
            Task(index='C1',position=(18,16),level=1.0),
            Task(index='C2',position=(16,16),level=1.0),
            Task(index='C3',position=(16,18),level=1.0),
        Task(index='D0',position=(1,18),level=1.0),
            Task(index='D1',position=(3,18),level=1.0),
            Task(index='D2',position=(3,16),level=1.0),
            Task(index='D3',position=(1,16),level=1.0),
            ],
    'obstacles':[]
}